// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CacheService measures and empties Hermit's download cache: mod archives
 * kept after installing them, GitHub release files and Thunderstore data.
 * Everything there is fetched again when it is needed, so clearing it only
 * costs downloads; installed mods live in the profiles and are not touched.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Clear deletes everything in the cache and returns how many bytes it freed.
 * The folder itself stays, since the clients write into it without creating
 * it first.
 */
export function Clear(): $CancellablePromise<number> {
    return $Call.ByID(910869254);
}

/**
 * Size returns the bytes the cache takes up.
 */
export function Size(): $CancellablePromise<number> {
    return $Call.ByID(1811163488);
}
