// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FolderService opens Hermit's folders in the desktop's file manager, for
 * looking at a profile's files or dropping something in by hand.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * OpenProfile shows a profile's folder: the mods, configs and BepInEx files
 * that are linked into the game while it runs.
 */
export function OpenProfile(gameID: string, profileID: string): $CancellablePromise<void> {
    return $Call.ByID(885607252, gameID, profileID);
}
