// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as github$0 from "../github/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as library$0 from "../library/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as modinstall$0 from "../modinstall/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BepInExBuild reports which BepInEx release a game would get from GitHub.
 */
export function BepInExBuild(gameID: string): $CancellablePromise<$models.BepInExBuild> {
    return $Call.ByID(4051463839, gameID);
}

/**
 * CheckUpdates lists installed Thunderstore mods with a newer version.
 */
export function CheckUpdates(gameID: string, profileID: string): $CancellablePromise<modinstall$0.Update[] | null> {
    return $Call.ByID(306278890, gameID, profileID);
}

/**
 * DownloadGitHubAsset downloads a release file and suggests how to name the
 * mod: from its manifest if it has one, otherwise after the repository and tag.
 */
export function DownloadGitHubAsset(owner: string, repo: string, tag: string, asset: github$0.Asset): $CancellablePromise<modinstall$0.LocalPackage> {
    return $Call.ByID(3591543941, owner, repo, tag, asset);
}

/**
 * GitHubReleases lists the releases of a repository given as owner/repo or URL.
 */
export function GitHubReleases(input: string): $CancellablePromise<$models.GitHubRepo> {
    return $Call.ByID(821711473, input);
}

/**
 * InspectFile reads a .zip or .dll mod file and suggests its author, name and version.
 */
export function InspectFile(path: string): $CancellablePromise<modinstall$0.LocalPackage> {
    return $Call.ByID(2133734766, path);
}

/**
 * InstallBepInEx installs that release into a profile as a mod, so it is
 * listed, disabled and updated like the Thunderstore packs are.
 */
export function InstallBepInEx(gameID: string, profileID: string): $CancellablePromise<library$0.Profile> {
    return $Call.ByID(1848044912, gameID, profileID);
}

/**
 * InstallFile installs a local mod file.
 */
export function InstallFile(gameID: string, profileID: string, pkg: modinstall$0.LocalPackage, replaceConflicts: boolean): $CancellablePromise<library$0.Profile> {
    return $Call.ByID(2681568897, gameID, profileID, pkg, replaceConflicts);
}

/**
 * InstallGitHub installs a downloaded release file as a mod that can be updated from GitHub.
 */
export function InstallGitHub(gameID: string, profileID: string, pkg: modinstall$0.LocalPackage, owner: string, repo: string, tag: string, asset: string, replaceConflicts: boolean): $CancellablePromise<library$0.Profile> {
    return $Call.ByID(3207824252, gameID, profileID, pkg, owner, repo, tag, asset, replaceConflicts);
}

/**
 * InstallModpack creates a new profile from a Thunderstore modpack.
 */
export function InstallModpack(gameID: string, $namespace: string, name: string, version: string, profileName: string): $CancellablePromise<library$0.Profile> {
    return $Call.ByID(2207740552, gameID, $namespace, name, version, profileName);
}

/**
 * InstallPackage installs a Thunderstore package version with its dependencies
 * into a profile, emitting InstallProgressEvent along the way. Conflicting
 * installed mods are uninstalled only if opts.ReplaceConflicts is set.
 */
export function InstallPackage(gameID: string, profileID: string, $namespace: string, name: string, version: string, opts: modinstall$0.Options): $CancellablePromise<library$0.Profile> {
    return $Call.ByID(1680772357, gameID, profileID, $namespace, name, version, opts);
}

/**
 * LoaderStatus reports whether a profile has a mod loader, whichever way it
 * got there: a Thunderstore pack, a GitHub release or a local archive. Without
 * one Hermit links nothing into the game and it starts vanilla.
 */
export function LoaderStatus(gameID: string, profileID: string): $CancellablePromise<$models.LoaderStatus> {
    return $Call.ByID(3651530457, gameID, profileID);
}

/**
 * OpenProfile returns a profile with mod states brought up to date.
 */
export function OpenProfile(gameID: string, profileID: string): $CancellablePromise<library$0.Profile> {
    return $Call.ByID(2915043105, gameID, profileID);
}

/**
 * PlanFile reports conflicts of installing a local or downloaded mod file.
 */
export function PlanFile(gameID: string, profileID: string, pkg: modinstall$0.LocalPackage): $CancellablePromise<modinstall$0.InstallPlan> {
    return $Call.ByID(33992953, gameID, profileID, pkg);
}

/**
 * PlanInstall downloads a package with its dependencies and reports what
 * installing it would change, including conflicts with installed mods.
 */
export function PlanInstall(gameID: string, profileID: string, $namespace: string, name: string, version: string, opts: modinstall$0.Options): $CancellablePromise<modinstall$0.InstallPlan> {
    return $Call.ByID(175763358, gameID, profileID, $namespace, name, version, opts);
}

/**
 * SetModEnabled enables or disables a mod; dependants follow automatically.
 */
export function SetModEnabled(gameID: string, profileID: string, modID: string, enabled: boolean): $CancellablePromise<library$0.Profile> {
    return $Call.ByID(2812849217, gameID, profileID, modID, enabled);
}

export function UninstallMod(gameID: string, profileID: string, modID: string): $CancellablePromise<library$0.Profile> {
    return $Call.ByID(465513794, gameID, profileID, modID);
}

/**
 * UpdateAll updates every outdated mod, emitting InstallProgressEvent.
 */
export function UpdateAll(gameID: string, profileID: string): $CancellablePromise<modinstall$0.UpdateResult> {
    return $Call.ByID(4173545652, gameID, profileID);
}

/**
 * UpdateMod updates one Thunderstore or GitHub mod to its latest version.
 */
export function UpdateMod(gameID: string, profileID: string, modID: string): $CancellablePromise<library$0.Profile> {
    return $Call.ByID(2266433523, gameID, profileID, modID);
}
