// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as launch$0 from "../launch/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetLaunchInfo(gameID: string): $CancellablePromise<$models.LaunchInfo> {
    return $Call.ByID(1209504583, gameID);
}

/**
 * GetLaunchReport returns what BepInEx loaded during the last session of a
 * profile, or nil if the profile was not launched with mods yet.
 */
export function GetLaunchReport(gameID: string, profileID: string): $CancellablePromise<launch$0.Report | null> {
    return $Call.ByID(1812944685, gameID, profileID);
}

/**
 * ListExecutables returns the .exe files a game could be started from,
 * relative to its folder: the game's own executable first, then any other
 * found a few levels deep, such as a launcher a mod asks to start the game
 * with.
 */
export function ListExecutables(gameID: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(3136976965, gameID);
}

/**
 * Play makes the profile active and starts the game through Steam. Mods load
 * only if the game's launch options run it through the wrapper.
 */
export function Play(gameID: string, profileID: string): $CancellablePromise<void> {
    return $Call.ByID(3396312206, gameID, profileID);
}

/**
 * PlayViaPortProton makes the profile active and starts the game through
 * PortProton, wrapped in "run" so the profile is linked in for the session.
 * The wrapper is a process of its own: the game outlives Hermit's window, and
 * the links are still removed when it exits.
 */
export function PlayViaPortProton(gameID: string, profileID: string): $CancellablePromise<void> {
    return $Call.ByID(3429716921, gameID, profileID);
}
