// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as configs$0 from "../configs/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as github$0 from "../github/models.js";

export interface AppInfo {
    "name": string;
    "version": string;
    "os": string;
    "arch": string;

    /**
     * SteamDeck reports whether Hermit runs on a Steam Deck, which decides
     * the interface layout when the UI mode is set to auto.
     */
    "steamDeck": boolean;
    "repository": string;
}

/**
 * BepInExBuild is the release file a game needs.
 */
export interface BepInExBuild {
    "tag": string;
    "version": string;
    "asset": string;
    "size": number;

    /**
     * Prerelease is true for BepInEx 6: IL2CPP support has no stable release
     * yet, so IL2CPP games get a pre-release build.
     */
    "prerelease": boolean;
    "url": string;
}

export interface ConfigContent {
    "path": string;
    "text": string;

    /**
     * Document is the parsed structure of .cfg files, nil for other files.
     */
    "document": configs$0.Document | null;
}

export interface GitHubRepo {
    "owner": string;
    "repo": string;
    "releases": github$0.Release[] | null;
}

export interface LaunchInfo {
    /**
     * Supported is false when the manager cannot launch the game with mods;
     * Reason explains why.
     */
    "supported": boolean;
    "reason": string;

    /**
     * LaunchOptions is the value to put into the game's Steam Launch Options.
     */
    "launchOptions": string;

    /**
     * External is true for games Steam does not start: Hermit can neither
     * start them itself nor read their launcher's settings, so the user
     * puts LaunchPrefix into whatever launcher runs the game.
     */
    "external": boolean;

    /**
     * LaunchPrefix is the wrapper to put in front of the game command in
     * launchers that take a command prefix, such as Lutris or Heroic.
     */
    "launchPrefix": string;

    /**
     * PortProton is true when an external Windows game can be started through
     * the PortProton Flatpak, which has nowhere to put a prefix, so Hermit
     * starts it itself.
     */
    "portProton": boolean;

    /**
     * Configured reports whether Steam's saved config has these launch options.
     * Steam writes its config lazily, so false may just mean "not saved yet".
     */
    "configured": boolean;
    "running": boolean;

    /**
     * RunningProfile is the profile of the running session, if any.
     */
    "runningProfile": string;
}

/**
 * LoaderStatus describes the mod loader of a profile, if it has one.
 */
export interface LoaderStatus {
    "installed": boolean;
    "modId"?: string;
    "name"?: string;
    "version"?: string;

    /**
     * Enabled is the user's choice; a disabled loader leaves the game vanilla.
     */
    "enabled": boolean;
}

/**
 * SteamSetup is what the interface needs to know to offer the shortcut.
 */
export interface SteamSetup {
    /**
     * Supported is false when there is no Steam to add anything to.
     */
    "supported": boolean;

    /**
     * Reason says why it is not supported.
     */
    "reason": string;

    /**
     * Added is true once Steam lists a shortcut to this very build.
     */
    "added": boolean;

    /**
     * Running reports whether Steam is running: adding the shortcut has to
     * restart it, because Steam rewrites its shortcuts when it exits.
     */
    "running": boolean;

    /**
     * Exe is the path Steam would start.
     */
    "exe": string;
}

/**
 * Update is the answer to "is there a newer Hermit?". Hermit does not install
 * itself: the user downloads the release.
 */
export interface Update {
    "current": string;
    "latest": string;
    "available": boolean;

    /**
     * URL is the release page, empty when nothing was found.
     */
    "url": string;
}
