// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SteamService adds Hermit itself to Steam as a non-Steam game, which is the
 * only way to start it from Game Mode on a Steam Deck.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddToSteam adds Hermit to every Steam user's shortcuts. Steam is closed
 * first if it runs, and started again afterwards, since it keeps the list in
 * memory and writes it back on exit.
 */
export function AddToSteam(): $CancellablePromise<$models.SteamSetup> {
    return $Call.ByID(3028269953);
}

export function GetSetup(): $CancellablePromise<$models.SteamSetup> {
    return $Call.ByID(2567469966);
}
