// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Issue is a plugin BepInEx refused or failed to load.
 */
export interface Issue {
    "kind": IssueKind;

    /**
     * Plugin is how BepInEx names the plugin: "<name> <version>".
     */
    "plugin": string;

    /**
     * Detail is the rest of the message, e.g. the incompatible plugin GUIDs.
     */
    "detail": string;

    /**
     * ModID is the installed mod the plugin most likely belongs to, if known.
     */
    "modId": string;
}

export enum IssueKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    IssueIncompatible = "incompatible",
    IssueMissingDependencies = "missing_dependencies",
    IssueDependencyNotLoaded = "dependency_not_loaded",
    IssueNewerVersionExists = "newer_version_exists",
    IssueProcessFilter = "process_filter",
    IssueLoadError = "load_error",
};

/**
 * Report summarises BepInEx's LogOutput.log of the last game session of a profile.
 */
export interface Report {
    "profileId": string;
    "startedAt": string;
    "finishedAt": string;

    /**
     * BepInExStarted is false when the log was not written during the session,
     * i.e. BepInEx did not load at all.
     */
    "bepinexStarted": boolean;
    "bepinexVersion": string;
    "loaded": string[] | null;
    "issues": Issue[] | null;

    /**
     * Complete is set once BepInEx says it finished loading plugins. A log
     * that stops before that means the game hung or crashed while a plugin
     * was starting: the last one in Loaded.
     */
    "complete": boolean;

    /**
     * Errors counts error lines from any source, BepInEx or the mods and the
     * game logging through it. Thousands of them usually mean mods written
     * for another version of the game.
     */
    "errors": number;

    /**
     * PluginMods is how many active mods of the profile carry BepInEx
     * plugins, and NotStarted lists those of them BepInEx never began to
     * load: the numbers to compare when a game starts to a black screen.
     */
    "pluginMods": number;
    "notStarted": string[] | null;
}
